### ISSUE TITLE
CMD closing after download start

### ISSUE THREAD

**Issue by Jon1Games** [Someone266/aniworld-downloader#1]
Hello,

So my problem is that the cmd is closing after starting the download.

That i did:
1. I just first started the program through the .exe
2. Made the setup (choosing using the offline web gui)
3. used the download helper and searched for: "That time i got reincarnated as a slime"
4. Chossen anime "1" was listed after the search
5. program searched for seasons and episodes
6. choosen to download all seasons
7. cmd closed 

I noticed the download folder for the anime is created and got image.jpg, info.html, info.json and stream.json

Thankyou for your help.

EDIT:
The Template has wrong relative paths, insted of "../../x" there is only one "../x" needed.
Also then i click on streams it tries to open "streams.json" which does not exits, is the file "stream.json" meaned?

**Comment by JMcrafter26** [comment]
Could you run the exe trough a terminal?
(Open cmd, cd into the folder, ./AniWorld.exe and then provide the error message)

**Comment by Someone266** [comment]
So it turns out the vow Downloader I am using does not work because vow updated Their site. I will fix it as soon as I get back

**Comment by Jon1Games** [comment]
I only saw it now sorry @JMcrafter26 ... Nice that you found the problem @Someone266,  im looking forward to the fix!

**Comment by Someone266** [comment]
It should work now. No need to manually update. The downloader will update itself automatically to the version 1.1.5

**Comment by Jon1Games** [comment]
Yeah wokes so far, I just don´t ask why two account xD... So i noticed that the offline web server doesn´t load the css correkt which i think is because of the `../../x.css` in the html files and coud be fixed by replacing it with `../x.css` and the same with the scripts(worked for me). Also the videos player isn´t finding the videos(this coud be because the downloader not finished all episodes yet), I think the problem with the video player is caused because of the location the script is searching for the video files which is `anime/video/season/episode.mp4` but the episodes are in the folder where the .exe is located.
