### ISSUE TITLE
Error/Crash when downloading 'Monster'

### ISSUE THREAD

**Issue by xVotexX** [Someone266/aniworld-downloader#10]
Just tried it out for the first time and there was this error. Other Anime seem to work fine as shown in the gif below.

![opera_2Lg2NdWP7G](https://github.com/user-attachments/assets/5990c6fc-39c1-4d7a-9240-1d0f2b676342)

Error:
![Bild_2024-08-01_161945904](https://github.com/user-attachments/assets/1ea4e704-33c8-4ca9-887b-e18509e32045)

**Comment by xVotexX** [comment]
Eben erst realisiert dass das ganze repo auf deutsch ist ^^

**Comment by JMcrafter26** [comment]
Hi, ich bin gerade im Urlaub und kann deshalb grade leider nicht die Fehler beheben. Ich verspreche aber, dass wenn ich wieder zurück bin, ich die Fehler beheben werde.

**Comment by xVotexX** [comment]
Alles gut :) Viel Spaß im Urlaub 👍

**Comment by JMcrafter26** [comment]
Es hat sich zwar alles etwas verzögert, aber ich habe den Bug (hoffentlich) behoben. (Monster hatte keinen Trailer, deshalb ist das Programm gecrashed)

**Comment by JMcrafter26** [comment]
Hi,
Ich habe vor ein paar Wochen ein Update herausgebracht. Mich würde es sehr interessieren ob der Fehler behoben wurde.
Danke :)

**Comment by xVotexX** [comment]
Sorry, ich war bis gestern im Urlaub. Ich werde es später Testen :)

**Comment by xVotexX** [comment]
Das herunterladen aller Episoden scheint zu funktionieren. Allerdings crasht es immer noch wenn man bestimmte Episoden herunterladen möchte (siehe gif:). 

![opera_FEEJOtk5Pt](https://github.com/user-attachments/assets/db4366ed-13df-449f-94c0-bcf837590158)

**Comment by JMcrafter26** [comment]
Achso, das meinst du.
Dieser bug besteht schon länger und ich habe jedes mal vergessen ihn zu beheben 😶‍🌫️

**Comment by xVotexX** [comment]
Ist ja keine große sache. Das eigentliche problem, das es beim download aller Episoden von Monster crasht, ist ja behoben :)

**Comment by JMcrafter26** [comment]
Dann ist ja gut.
Ich werde den bug in Zukunft definitiv beheben und dann kann man dieses Issue ja schließen :)
