### ISSUE TITLE
OfflineWeb GUI not loading/redirecting properly

### ISSUE THREAD

**Issue by Jon1Games** [Someone266/aniworld-downloader#2]
Hello again,
So I used your web GUI and noticed what some pictures and path weren´t loading properly, then I saw that in the `index.json` the anime path was `anime/ANIME_NAME` and changed it to `AIME_NAME` and now it redirected me to the correct side and showed the picture at the index properly.
Then the Videos in the loader weren´t loading at first which a corrected by moving them into the right folder (`ANIME_NAME/video/season/episode.mp4`), before the were locatet in the same foler as the `.exe` file.
Lastly after I changed the location of the episodes to the other folders the videoplayer found the video, but didn´t started playing them. (I have tested to use the crome videoplayer for this episode to which didn´t worked as well.)
Thankyou for help!

**Comment by JMcrafter26** [comment]
I will look into it tomorrow

**Comment by JMcrafter26** [comment]
If you know how to fix it, you are welcome to open a pull request

**Comment by Jon1Games** [comment]
> If you know how to fix it, you are welcome to open a pull request

I´m not at home until next mounth, but I just know to to fix manually but idk where to fix it in the actually code... Coud go though it then I´m home again.

EDIT:
Hab gerade erstmal gesehen das du ja Deutsch bist xD... Ich denke ich könnte das mit dem falschen laden der seite fixen aber Speichern der Videos und den Video Player wüste ich jetzt spontan nicht.

**Comment by JMcrafter26** [comment]
Ich arbeite gerade daran.
Ich werde wahrscheinlich auch ein paar neue Features einbauen

**Comment by Someone266** [comment]
I released a new version. Please give it a try! (It will update automatically)

**Comment by Jon1Games** [comment]
I´ll test it as soon I´m back home.

**Comment by JMcrafter26** [comment]
Hi,
Ich habe vor ein paar Wochen ein Update herausgebracht. Mich würde es sehr interessieren ob der Fehler behoben wurde.
Danke :)

**Comment by Jon1Games** [comment]
> Hi, Ich habe vor ein paar Wochen ein Update herausgebracht. Mich würde es sehr interessieren ob der Fehler behoben wurde. Danke :)

Download ist gerade gestartet, weitere Informationen Folgen.

**Comment by Jon1Games** [comment]
Der Download und Speicherort sind super, die WEB GUI lädt auch gut.
Bei mir laden die Videos nicht, könnte aber auch durch aus an Einstellungen des web Servers (nginx) liegen oder am Browser.

EDIT:
Habs mal noch mit Edge probiert geht da auch nicht. Dan denke ich mal das dem web Server eine Einstellung fehlt.
