### ISSUE TITLE
FRAGE: Programm auf Deutsch übersetzen?

### ISSUE THREAD

**Issue by JMcrafter26** [Someone266/aniworld-downloader#5]
Das aktuelle Programm ist momentan komplett auf Englisch. Soll es eine deutsche Version davon geben?

Bitte antwortet mit einer Zahl von 1 bis 5:

1 - Wenig interessiert / Nicht nötig

5 - Stark interessiert / Dringend nötig

**Comment by Jon1Games** [comment]
2

Wie währe es wen du mit Configs arbeitest und eine Auswahl Möglichkeit bietest?
Gleiches währe auch für die Sprache des Downloads eine Idee.

**Comment by JMcrafter26** [comment]
Daran habe ich auch schon gedacht. Aber für so ein „einfaches“ Programm wäre das meiner Meinung nach zu viel Aufwand.
Das mit der Download Sprache wäre aber eine gute Idee

**Comment by palpex** [comment]
1 

I think for most users it’s not needed, but the possibility of changing the download language is pretty neat!
