### ISSUE TITLE
Crash bei der URL Eingabe

### ISSUE THREAD

**Issue by EvilBlood** [Someone266/aniworld-downloader#6]
Moin,
seit dem 22.07.  crasht die Version 1.1.5 und auch die neue 1.1.7. bei der URL Eingabe.

Die Datei liegt in: 
D:\Downloads\AniworldDown

Beispiel URLs:
https://aniworld.to/anime/stream/why-raeliana-ended-up-at-the-dukes-mansion
https://aniworld.to/anime/stream/dragonball
https://aniworld.to/anime/stream/dragonball-z-kai

im Terminal kommt folgender Output:
`D:\Downloads\AniworldDown> .\AniWorld-Down.exe
←[H←[J

←[96m    AA          W     W         ll     d     DDD                    ←[0m
←[96m   A  A      ii W     W          l     d     D  D                   ←[0m
←[96m   AAAA nnn     W  W  W ooo rrr  l   ddd     D  D ooo w   w nnn     ←[0m
←[96m   A  A n  n ii  W W W  o o r    l  d  d     D  D o o w w w n  n    ←[0m
←[96m   A  A n  n ii   W W   ooo r   lll  ddd     DDD  ooo  w w  n  n    ←[0m
←[96m                                                                    ←[0m
A powerful scraper and downloader for AniWorld

Version: 1.1.7 (Windows)                                 Made by JMcrafter26
←[90mDISCLAIMER: This is a scraper for educational purposes only. I am not responsible for any misuse of this code.←[0m
←[90mPlease respect the laws of your country and the country of the website you are scraping.←[0m

Loading...
Checking for updates... Done
Downloading assets...
Downloading ..
←[92mDownload complete←[0m
←[92mUpdate complete←[0m

←[93mIt is recommended to run the ←[0m←[92mclean option←[0m←[93m after updating←[0m

←[H←[J

←[96m    AA          W     W         ll     d     DDD                    ←[0m
←[96m   A  A      ii W     W          l     d     D  D                   ←[0m
←[96m   AAAA nnn     W  W  W ooo rrr  l   ddd     D  D ooo w   w nnn     ←[0m
←[96m   A  A n  n ii  W W W  o o r    l  d  d     D  D o o w w w n  n    ←[0m
←[96m   A  A n  n ii   W W   ooo r   lll  ddd     DDD  ooo  w w  n  n    ←[0m
←[96m                                                                    ←[0m
A powerful scraper and downloader for AniWorld

Version: 1.1.7 (Windows)                                 Made by JMcrafter26
←[90mDISCLAIMER: This is a scraper for educational purposes only. I am not responsible for any misuse of this code.←[0m
←[90mPlease respect the laws of your country and the country of the website you are scraping.←[0m

←[H←[J

←[96m    AA          W     W         ll     d     DDD                    ←[0m
←[96m   A  A      ii W     W          l     d     D  D                   ←[0m
←[96m   AAAA nnn     W  W  W ooo rrr  l   ddd     D  D ooo w   w nnn     ←[0m
←[96m   A  A n  n ii  W W W  o o r    l  d  d     D  D o o w w w n  n    ←[0m
←[96m   A  A n  n ii   W W   ooo r   lll  ddd     DDD  ooo  w w  n  n    ←[0m
←[96m                                                                    ←[0m
A powerful scraper and downloader for AniWorld

Version: 1.1.7 (Windows)                                 Made by JMcrafter26
←[90mDISCLAIMER: This is a scraper for educational purposes only. I am not responsible for any misuse of this code.←[0m
←[90mPlease respect the laws of your country and the country of the website you are scraping.←[0m

Press one of the following keys:
1. Download Assistant
2. Continue Download
3. Serve content
4. Clean up
5. Open anime folder
6. Get anime info
0. Settings
h. Help/Info
q. Quit
1
←[H←[J

←[96m    AA          W     W         ll     d     DDD                    ←[0m
←[96m   A  A      ii W     W          l     d     D  D                   ←[0m
←[96m   AAAA nnn     W  W  W ooo rrr  l   ddd     D  D ooo w   w nnn     ←[0m
←[96m   A  A n  n ii  W W W  o o r    l  d  d     D  D o o w w w n  n    ←[0m
←[96m   A  A n  n ii   W W   ooo r   lll  ddd     DDD  ooo  w w  n  n    ←[0m
←[96m                                                                    ←[0m
A powerful scraper and downloader for AniWorld

Version: 1.1.7 (Windows)                                 Made by JMcrafter26
←[90mDISCLAIMER: This is a scraper for educational purposes only. I am not responsible for any misuse of this code.←[0m
←[90mPlease respect the laws of your country and the country of the website you are scraping.←[0m

←[92mThis is the auto mode. It will ask you what to ←[0m

Enter the name of the anime you want to search for or paste the url of the anime
https://aniworld.to/anime/stream/why-raeliana-ended-up-at-the-dukes-mansion
Traceback (most recent call last):
  File "main_win.py", line 530, in <module>
  File "main_win.py", line 513, in handleCommands
  File "main_win.py", line 303, in startUi
  File "main_win.py", line 466, in runAuto
UnboundLocalError: cannot access local variable 'C' where it is not associated with a value
[18912] Failed to execute script 'main_win' due to unhandled exception!
PS D:\Downloads\AniworldDown>`

**Comment by JMcrafter26** [comment]
Das mit dem url ist mir bewusst, wird im nächsten Update behoben
